from classe import Attaque

# Spéciale
Surf = Attaque('Surf', 'Eau', 90, 'Speciale')
Hydrocanon = Attaque('Hydrocanon', 'Eau', 110, 'Speciale')
Tonnerre = Attaque('Tonnerre', 'Electrik', 90, 'Speciale')
FatalFoudre = Attaque('Fatal-Foudre', 'Electrik', 110, 'Speciale')
LanceFlammes = Attaque('Lance-Flammes', 'Feu', 90, 'Speciale')
Déflagration = Attaque('Déflagration', 'Feu', 110, 'Speciale')
Telluriforce = Attaque('Telluriforce', 'Sol', 90, 'Speciale')
LaserGlace = Attaque('Laser Glace', 'Glace', 90, 'Speciale')
Blizzard = Attaque('Blizzard', 'Glace', 110, 'Speciale')
Psyko = Attaque('Psyko', 'Psy', 90, 'Speciale')
ChocPsy = Attaque('Choc Psy', 'Psy', 80, 'Speciale')
BallOmbre = Attaque('Ball’Ombre', 'Spectre', 80, 'Speciale')
Vibrobscur = Attaque('Vibrobscur', 'Ténèbres', 80, 'Speciale')
Ultralaser = Attaque('Ultralaser', 'Normal', 150, 'Speciale')
LanceSoleil = Attaque('Lance-Soleil', 'Plante', 120, 'Speciale')
ÉcoSphère = Attaque('Éco-Sphère', 'Plante', 90, 'Speciale')
Lance_flamme = Attaque('Lance Flamme', 'Feu', 90, 'Speciale')
Éclair = Attaque('Éclair', 'Electrik', 40, 'Speciale')
Ouragan = Attaque('Ouragan', 'Vol', 110, 'Speciale')
OndePsy = Attaque('Onde Psy', 'Psy', 60, 'Speciale')
OndeDeChoc = Attaque('Onde de Choc', 'Electrik', 60, 'Speciale')
BallGlace = Attaque('Ball Glace', 'Glace', 65, 'Speciale')

# Physique
Séisme = Attaque('Séisme', 'Sol', 100, 'Physique')
CasseBrique = Attaque('Casse-Brique', 'Combat', 75, 'Physique')
CloseCombat = Attaque('Close Combat', 'Combat', 120, 'Physique')
GigaImpact = Attaque('Giga Impact', 'Normal', 150, 'Physique')
LameFeuille = Attaque('Lame Feuille', 'Plante', 90, 'Physique')
Dracogriffe = Attaque('Dracogriffe', 'Dragon', 80, 'Physique')
Colère = Attaque('Colère', 'Dragon', 120, 'Physique')
Mâchouille = Attaque('Mâchouille', 'Ténèbres', 80, 'Physique')
PoingGlace = Attaque('Poing Glace', 'Glace', 75, 'Physique')
PoingÉclair = Attaque('Poing Éclair', 'Electrik', 75, 'Physique')
PoingFeu = Attaque('Poing Feu', 'Feu', 75, 'Physique')
LameDeRoc = Attaque('Lame de Roc', 'Roche', 100, 'Physique')
Éboulement = Attaque('Éboulement', 'Roche', 75, 'Physique')
BombBeurk = Attaque('Bomb-Beurk', 'Poison', 90, 'Speciale')
DardVenin = Attaque('Dard-Venin', 'Poison', 50, 'Physique')
Pistolet_a_eau = Attaque('Pistolet A Eau', 'Eau', 40, 'Physique')
Tacle = Attaque('Tacle', 'Normal', 40, 'Physique')
Griffe = Attaque('Griffe', 'Normal', 40, 'Physique')
Charge = Attaque('Charge', 'Normal', 40, 'Physique')
Hydroqueue = Attaque('Hydroqueue', 'Eau', 60, 'Physique')
DracoRage = Attaque('Draco-Rage', 'Dragon', 60, 'Physique')
Coupe = Attaque('Coupe', 'Normal', 50, 'Physique')
Léchouille = Attaque('Léchouille', 'Spectre', 20, 'Physique')
PoingDrain = Attaque('Poing-Drain', 'Combat', 75, 'Physique')
CrocsFeu = Attaque('Crocs Feu', 'Feu', 65, 'Physique')
CrocsGivre = Attaque('Crocs Givre', 'Glace', 65, 'Physique')
CrocsEclair = Attaque('Crocs Éclair', 'Electrik', 65, 'Physique')
Picpic = Attaque('Picpic', 'Vol', 25, 'Physique')
VoleVivres = Attaque('Vole-Vie', 'Spectre', 75, 'Physique')
AileAcier = Attaque("Aile d'Acier", 'Acier', 70, 'Physique')
Morsure = Attaque('Morsure', 'Ténèbres', 60, 'Physique')
CoupDeTete = Attaque("Coup de Tête", 'Normal', 70, 'Physique')
BecVrille = Attaque('Bec Vrille', 'Vol', 80, 'Physique')

# Statut
Vampigraine = Attaque('Vampigraine', 'Plante', 0, 'Statut')
Toxik = Attaque('Toxik', 'Poison', 0, 'Statut')
Abri = Attaque('Abri', 'Normal', 0, 'Statut')
DanseLames = Attaque('Danse-Lames', 'Normal', 0, 'Statut')
BoueBombe = Attaque('Boue-Bombe', 'Sol', 20, 'Speciale')
Luminocanon = Attaque('Luminocanon', 'Acier', 80, 'Speciale')
Atterrissage = Attaque('Atterrissage', 'Vol', 0, 'Statut')
Hurlement = Attaque('Hurlement', 'Normal', 0, 'Statut')
Repos = Attaque('Repos', 'Normal', 0, 'Statut')
Soin = Attaque('Soin', 'Normal', 0, 'Statut')
PiegeDeRoc = Attaque('Piège de Roc', 'Roche', 0, 'Statut')
