# Table de Loi des Types 
faiblesses_simple = {
    'Normal': {
        'faible_contre': ['Combat'],
        'resistant_contre': [],
        'inefficace_contre': ['Spectre']
    },
    'Feu': {
        'faible_contre': ['Eau', 'Sol', 'Roche'],
        'resistant_contre': ['Feu', 'Plante', 'Glace', 'Insecte', 'Acier', 'Fée'],
        'inefficace_contre': []
    },
    'Eau': {
        'faible_contre': ['Électrik', 'Plante'],
        'resistant_contre': ['Feu', 'Eau', 'Glace', 'Acier'],
        'inefficace_contre': []
    },
    'Plante': {
        'faible_contre': ['Feu', 'Glace', 'Poison', 'Vol', 'Insecte'],
        'resistant_contre': ['Eau', 'Électrik', 'Plante', 'Sol'],
        'inefficace_contre': []
    },
    'Électrik': {
        'faible_contre': ['Sol'],
        'resistant_contre': ['Électrik', 'Vol', 'Acier'],
        'inefficace_contre': []
    },
    'Glace': {
        'faible_contre': ['Feu', 'Combat', 'Roche', 'Acier'],
        'resistant_contre': ['Glace'],
        'inefficace_contre': []
    },
    'Combat': {
        'faible_contre': ['Vol', 'Psy', 'Fée'],
        'resistant_contre': ['Insecte', 'Roche', 'Ténèbres'],
        'inefficace_contre': []
    },
    'Poison': {
        'faible_contre': ['Sol', 'Psy'],
        'resistant_contre': ['Plante', 'Combat', 'Poison', 'Fée', 'Insecte'],
        'inefficace_contre': []
    },
    'Sol': {
        'faible_contre': ['Eau', 'Plante', 'Glace'],
        'resistant_contre': ['Poison', 'Roche'],
        'inefficace_contre': ['Électrik']
    },
    'Vol': {
        'faible_contre': ['Électrik', 'Glace', 'Roche'],
        'resistant_contre': ['Plante', 'Combat', 'Insecte'],
        'inefficace_contre': ['Sol']
    },
    'Psy': {
        'faible_contre': ['Insecte', 'Spectre', 'Ténèbres'],
        'resistant_contre': ['Combat', 'Psy'],
        'inefficace_contre': []
    },
    'Insecte': {
        'faible_contre': ['Feu', 'Vol', 'Roche'],
        'resistant_contre': ['Plante', 'Combat', 'Sol'],
        'inefficace_contre': []
    },
    'Roche': {
        'faible_contre': ['Eau', 'Plante', 'Combat', 'Sol', 'Acier'],
        'resistant_contre': ['Normal', 'Feu', 'Poison', 'Vol'],
        'inefficace_contre': []
    },
    'Spectre': {
        'faible_contre': ['Spectre', 'Ténèbres'],
        'resistant_contre': ['Poison', 'Insecte'],
        'inefficace_contre': ['Normal', 'Combat']
    },
    'Dragon': {
        'faible_contre': ['Glace', 'Dragon', 'Fée'],
        'resistant_contre': ['Feu', 'Eau', 'Électrik', 'Plante'],
        'inefficace_contre': []
    },
    'Ténèbres': {
        'faible_contre': ['Combat', 'Insecte', 'Fée'],
        'resistant_contre': ['Spectre', 'Ténèbres'],
        'inefficace_contre': ['Psy']
    },
    'Acier': {
        'faible_contre': ['Feu', 'Combat', 'Sol'],
        'resistant_contre': ['Normal', 'Plante', 'Glace', 'Vol', 'Psy', 'Insecte', 'Roche', 'Dragon', 'Acier', 'Fée'],
        'inefficace_contre': ['Poison']
    },
    'Fée': {
        'faible_contre': ['Poison', 'Acier'],
        'resistant_contre': ['Combat', 'Insecte', 'Ténèbres'],
        'inefficace_contre': ['Dragon']
    }
}

# Fichier complet des faiblesses et résistances pour tous les doubles types Pokémon
faiblesses_double = {
    'Normal/Feu': {'faible_contre': ['Eau', 'Sol', 'Roche', 'Combat'], 'resistant_contre': ['Feu', 'Plante', 'Glace', 'Insecte', 'Acier', 'Fée'], 'inefficace_contre': ['Spectre']},
    'Normal/Eau': {'faible_contre': ['Électrik', 'Plante', 'Combat'], 'resistant_contre': ['Feu', 'Eau', 'Glace', 'Acier'], 'inefficace_contre': ['Spectre']},
    'Normal/Plante': {'faible_contre': ['Feu', 'Glace', 'Poison', 'Vol', 'Insecte', 'Combat'], 'resistant_contre': ['Eau', 'Électrik', 'Plante', 'Sol'], 'inefficace_contre': ['Spectre']},
    'Normal/Électrik': {'faible_contre': ['Sol', 'Combat'], 'resistant_contre': ['Électrik', 'Vol', 'Acier'], 'inefficace_contre': ['Spectre']},
    'Normal/Glace': {'faible_contre': ['Feu', 'Combat', 'Roche', 'Acier'], 'resistant_contre': ['Glace'], 'inefficace_contre': ['Spectre']},
    'Normal/Combat': {'faible_contre': ['Vol', 'Psy'], 'resistant_contre': ['Insecte', 'Roche', 'Ténèbres'], 'inefficace_contre': ['Spectre']},
    'Normal/Poison': {'faible_contre': ['Sol', 'Psy', 'Combat'], 'resistant_contre': ['Plante', 'Poison', 'Fée', 'Insecte'], 'inefficace_contre': ['Spectre']},
    'Normal/Sol': {'faible_contre': ['Eau', 'Plante', 'Glace', 'Combat'], 'resistant_contre': ['Poison', 'Roche'], 'inefficace_contre': ['Électrik', 'Spectre']},
    'Normal/Vol': {'faible_contre': ['Électrik', 'Glace', 'Roche', 'Combat'], 'resistant_contre': ['Plante', 'Insecte'], 'inefficace_contre': ['Sol', 'Spectre']},
    'Normal/Psy': {'faible_contre': ['Insecte', 'Spectre', 'Ténèbres', 'Combat'], 'resistant_contre': ['Psy'], 'inefficace_contre': ['Spectre']},
    'Normal/Insecte': {'faible_contre': ['Feu', 'Vol', 'Roche', 'Combat'], 'resistant_contre': ['Plante', 'Sol'], 'inefficace_contre': ['Spectre']},
    'Normal/Roche': {'faible_contre': ['Eau', 'Plante', 'Combat', 'Sol', 'Acier'], 'resistant_contre': ['Normal', 'Feu', 'Poison', 'Vol'], 'inefficace_contre': ['Spectre']},
    'Normal/Spectre': {'faible_contre': ['Spectre', 'Ténèbres', 'Combat'], 'resistant_contre': ['Poison', 'Insecte'], 'inefficace_contre': ['Normal', 'Spectre']},
    'Normal/Dragon': {'faible_contre': ['Glace', 'Dragon', 'Fée', 'Combat'], 'resistant_contre': ['Feu', 'Eau', 'Électrik', 'Plante'], 'inefficace_contre': ['Spectre']},
    'Normal/Ténèbres': {'faible_contre': ['Combat', 'Insecte', 'Fée'], 'resistant_contre': ['Ténèbres'], 'inefficace_contre': ['Psy', 'Spectre']},
    'Normal/Acier': {'faible_contre': ['Feu', 'Combat', 'Sol'], 'resistant_contre': ['Normal', 'Plante', 'Glace', 'Vol', 'Psy', 'Insecte', 'Roche', 'Dragon', 'Acier', 'Fée'], 'inefficace_contre': ['Poison', 'Spectre']},
    'Normal/Fée': {'faible_contre': ['Poison', 'Acier', 'Combat'], 'resistant_contre': ['Insecte', 'Ténèbres'], 'inefficace_contre': ['Dragon', 'Spectre']},

    # Types Fée combinés
    'Fée/Feu': {'faible_contre': ['Poison', 'Acier', 'Sol', 'Eau', 'Roche'], 'resistant_contre': ['Combat', 'Insecte', 'Ténèbres', 'Feu', 'Fée'], 'inefficace_contre': ['Dragon']},
    'Fée/Eau': {'faible_contre': ['Électrik', 'Plante', 'Poison', 'Acier'], 'resistant_contre': ['Combat', 'Insecte', 'Ténèbres', 'Feu', 'Fée'], 'inefficace_contre': ['Dragon']},
    'Fée/Plante': {'faible_contre': ['Feu', 'Glace', 'Poison', 'Vol', 'Insecte', 'Acier'], 'resistant_contre': ['Combat', 'Insecte', 'Ténèbres', 'Eau', 'Électrik', 'Plante', 'Sol', 'Fée'], 'inefficace_contre': ['Dragon']},
    'Fée/Électrik': {'faible_contre': ['Sol', 'Poison', 'Acier'], 'resistant_contre': ['Combat', 'Insecte', 'Ténèbres', 'Électrik', 'Vol', 'Fée'], 'inefficace_contre': ['Dragon']},
    'Fée/Glace': {'faible_contre': ['Feu', 'Combat', 'Roche', 'Acier', 'Poison'], 'resistant_contre': ['Combat', 'Insecte', 'Ténèbres', 'Glace', 'Fée'], 'inefficace_contre': ['Dragon']},
    'Fée/Combat': {'faible_contre': ['Vol', 'Psy', 'Fée', 'Poison', 'Acier'], 'resistant_contre': ['Insecte', 'Roche', 'Ténèbres', 'Fée'], 'inefficace_contre': ['Dragon']},
    'Fée/Poison': {'faible_contre': ['Sol', 'Psy', 'Poison', 'Acier'], 'resistant_contre': ['Plante', 'Fée'], 'inefficace_contre': ['Dragon']},
    'Fée/Sol': {'faible_contre': ['Eau', 'Plante', 'Glace', 'Poison', 'Acier'], 'resistant_contre': ['Poison', 'Roche', 'Fée'], 'inefficace_contre': ['Dragon']},
    'Fée/Vol': {'faible_contre': ['Électrik', 'Glace', 'Roche', 'Poison', 'Acier'], 'resistant_contre': ['Plante', 'Insecte', 'Fée'], 'inefficace_contre': ['Dragon']},
    'Fée/Psy': {'faible_contre': ['Insecte', 'Spectre', 'Ténèbres', 'Poison', 'Acier'], 'resistant_contre': ['Psy', 'Fée'], 'inefficace_contre': ['Dragon']},
    'Fée/Insecte': {'faible_contre': ['Feu', 'Vol', 'Roche', 'Poison', 'Acier'], 'resistant_contre': ['Plante', 'Fée'], 'inefficace_contre': ['Dragon']},
    'Fée/Roche': {'faible_contre': ['Eau', 'Plante', 'Combat', 'Sol', 'Acier'], 'resistant_contre': ['Fée'], 'inefficace_contre': ['Dragon']},
    'Fée/Spectre': {'faible_contre': ['Spectre', 'Ténèbres', 'Poison', 'Acier'], 'resistant_contre': ['Fée'], 'inefficace_contre': ['Dragon']},
    'Fée/Dragon': {'faible_contre': ['Glace', 'Dragon', 'Fée', 'Acier'], 'resistant_contre': ['Fée'], 'inefficace_contre': ['Dragon']},
    'Fée/Ténèbres': {'faible_contre': ['Combat', 'Insecte', 'Fée', 'Poison', 'Acier'], 'resistant_contre': ['Spectre', 'Ténèbres', 'Fée'], 'inefficace_contre': ['Dragon']},
    'Fée/Acier': {'faible_contre': ['Feu', 'Combat', 'Sol', 'Poison', 'Acier'], 'resistant_contre': ['Normal', 'Plante', 'Glace', 'Vol', 'Psy', 'Insecte', 'Roche', 'Dragon', 'Acier', 'Fée'], 'inefficace_contre': ['Dragon']},

    # Types Ténèbres combinés
    'Ténèbres/Feu': {'faible_contre': ['Combat', 'Insecte', 'Fée', 'Eau', 'Sol', 'Roche'], 'resistant_contre': ['Spectre', 'Ténèbres', 'Feu', 'Insecte'], 'inefficace_contre': ['Psy']},
    'Ténèbres/Eau': {'faible_contre': ['Électrik', 'Plante', 'Combat', 'Insecte', 'Fée'], 'resistant_contre': ['Ténèbres', 'Feu', 'Eau', 'Glace', 'Acier'], 'inefficace_contre': ['Psy']},
    'Ténèbres/Plante': {'faible_contre': ['Feu', 'Glace', 'Poison', 'Vol', 'Insecte', 'Combat', 'Fée'], 'resistant_contre': ['Ténèbres', 'Eau', 'Électrik', 'Plante', 'Sol'], 'inefficace_contre': ['Psy']},
    'Ténèbres/Électrik': {'faible_contre': ['Sol', 'Combat', 'Insecte', 'Fée'], 'resistant_contre': ['Ténèbres', 'Électrik', 'Vol', 'Acier'], 'inefficace_contre': ['Psy']},
    'Ténèbres/Glace': {'faible_contre': ['Feu', 'Combat', 'Roche', 'Acier', 'Insecte', 'Fée'], 'resistant_contre': ['Ténèbres', 'Glace'], 'inefficace_contre': ['Psy']},
    'Ténèbres/Combat': {'faible_contre': ['Vol', 'Psy', 'Insecte', 'Fée'], 'resistant_contre': ['Ténèbres', 'Roche'], 'inefficace_contre': ['Psy']},
    'Ténèbres/Poison': {'faible_contre': ['Sol', 'Psy', 'Insecte', 'Fée'], 'resistant_contre': ['Ténèbres', 'Plante', 'Poison'], 'inefficace_contre': ['Psy']},
    'Ténèbres/Sol': {'faible_contre': ['Eau', 'Plante', 'Glace', 'Combat', 'Insecte', 'Fée'], 'resistant_contre': ['Ténèbres', 'Poison', 'Roche'], 'inefficace_contre': ['Électrik', 'Psy']},
    'Ténèbres/Vol': {'faible_contre': ['Électrik', 'Glace', 'Roche', 'Combat', 'Insecte', 'Fée'], 'resistant_contre': ['Ténèbres', 'Plante', 'Insecte'], 'inefficace_contre': ['Sol', 'Psy']},
    'Ténèbres/Psy': {'faible_contre': ['Insecte', 'Spectre', 'Ténèbres', 'Combat', 'Fée'], 'resistant_contre': ['Ténèbres', 'Psy'], 'inefficace_contre': ['Psy']},
    'Ténèbres/Insecte': {'faible_contre': ['Feu', 'Vol', 'Roche', 'Combat', 'Insecte', 'Fée'], 'resistant_contre': ['Ténèbres', 'Plante', 'Sol'], 'inefficace_contre': ['Psy']},
    'Ténèbres/Roche': {'faible_contre': ['Eau', 'Plante', 'Combat', 'Sol', 'Acier', 'Insecte', 'Fée'], 'resistant_contre': ['Ténèbres', 'Normal', 'Feu', 'Poison', 'Vol'], 'inefficace_contre': ['Psy']},
    'Ténèbres/Spectre': {'faible_contre': ['Spectre', 'Ténèbres', 'Combat', 'Insecte', 'Fée'], 'resistant_contre': ['Ténèbres', 'Poison', 'Insecte'], 'inefficace_contre': ['Normal', 'Spectre', 'Psy']},
    'Ténèbres/Dragon': {'faible_contre': ['Glace', 'Dragon', 'Fée', 'Combat', 'Insecte', 'Fée'], 'resistant_contre': ['Ténèbres', 'Feu', 'Eau', 'Électrik', 'Plante'], 'inefficace_contre': ['Psy']},
    'Ténèbres/Ténèbres': {'faible_contre': ['Combat', 'Insecte', 'Fée'], 'resistant_contre': ['Ténèbres'], 'inefficace_contre': ['Psy']},
    'Ténèbres/Acier': {'faible_contre': ['Feu', 'Combat', 'Sol', 'Insecte', 'Fée'], 'resistant_contre': ['Ténèbres', 'Normal', 'Plante', 'Glace', 'Vol', 'Psy', 'Roche', 'Dragon', 'Acier'], 'inefficace_contre': ['Poison', 'Psy']},
    'Ténèbres/Fée': {'faible_contre': ['Poison', 'Acier', 'Combat', 'Insecte', 'Fée'], 'resistant_contre': ['Ténèbres', 'Spectre', 'Fée'], 'inefficace_contre': ['Dragon', 'Psy']},

    # Types Acier combinés
    'Acier/Feu': {'faible_contre': ['Combat', 'Sol'], 'resistant_contre': ['Normal', 'Plante', 'Glace', 'Vol', 'Psy', 'Insecte', 'Roche', 'Dragon', 'Acier', 'Fée', 'Feu', 'Insecte'], 'inefficace_contre': ['Poison']},
    'Acier/Eau': {'faible_contre': ['Combat', 'Sol', 'Électrik'], 'resistant_contre': ['Normal', 'Plante', 'Glace', 'Vol', 'Psy', 'Insecte', 'Roche', 'Dragon', 'Acier', 'Fée', 'Feu', 'Eau', 'Glace', 'Acier'], 'inefficace_contre': ['Poison']},
    'Acier/Plante': {'faible_contre': ['Feu', 'Combat', 'Sol'], 'resistant_contre': ['Normal', 'Plante', 'Glace', 'Vol', 'Psy', 'Insecte', 'Roche', 'Dragon', 'Acier', 'Fée', 'Eau', 'Électrik', 'Plante', 'Sol'], 'inefficace_contre': ['Poison']},
    'Acier/Électrik': {'faible_contre': ['Sol', 'Combat'], 'resistant_contre': ['Normal', 'Plante', 'Glace', 'Vol', 'Psy', 'Insecte', 'Roche', 'Dragon', 'Acier', 'Fée', 'Électrik', 'Vol'], 'inefficace_contre': ['Poison']},
    'Acier/Glace': {'faible_contre': ['Feu', 'Combat', 'Sol'], 'resistant_contre': ['Normal', 'Plante', 'Glace', 'Vol', 'Psy', 'Insecte', 'Roche', 'Dragon', 'Acier', 'Fée', 'Glace'], 'inefficace_contre': ['Poison']},
    'Acier/Combat': {'faible_contre': ['Feu', 'Sol'], 'resistant_contre': ['Normal', 'Plante', 'Glace', 'Vol', 'Psy', 'Insecte', 'Roche', 'Dragon', 'Acier', 'Fée', 'Insecte', 'Roche', 'Ténèbres'], 'inefficace_contre': ['Poison']},
    'Acier/Poison': {'faible_contre': ['Sol', 'Combat'], 'resistant_contre': ['Normal', 'Plante', 'Glace', 'Vol', 'Psy', 'Insecte', 'Roche', 'Dragon', 'Acier', 'Fée', 'Plante', 'Poison', 'Fée', 'Insecte'], 'inefficace_contre': ['Poison']},
    'Acier/Sol': {'faible_contre': ['Eau', 'Combat'], 'resistant_contre': ['Normal', 'Plante', 'Glace', 'Vol', 'Psy', 'Insecte', 'Roche', 'Dragon', 'Acier', 'Fée', 'Poison', 'Roche'], 'inefficace_contre': ['Électrik']},
    'Acier/Vol': {'faible_contre': ['Électrik', 'Feu', 'Sol'], 'resistant_contre': ['Normal', 'Plante', 'Glace', 'Vol', 'Psy', 'Insecte', 'Roche', 'Dragon', 'Acier', 'Fée', 'Plante', 'Insecte', 'Acier', 'Fée', 'Feu', 'Combat', 'Glace'], 'inefficace_contre': ['Sol']},
    'Acier/Psy': {'faible_contre': ['Combat', 'Sol'], 'resistant_contre': ['Normal', 'Plante', 'Glace', 'Vol', 'Psy', 'Insecte', 'Roche', 'Dragon', 'Acier', 'Fée', 'Combat', 'Psy', 'Insecte'], 'inefficace_contre': ['Poison']},
    'Acier/Insecte': {'faible_contre': ['Feu', 'Combat', 'Sol'], 'resistant_contre': ['Normal', 'Plante', 'Glace', 'Vol', 'Psy', 'Insecte', 'Roche', 'Dragon', 'Acier', 'Fée', 'Plante', 'Sol'], 'inefficace_contre': ['Poison']},
    'Acier/Roche': {'faible_contre': ['Eau', 'Combat', 'Sol'], 'resistant_contre': ['Normal', 'Plante', 'Glace', 'Vol', 'Psy', 'Insecte', 'Roche', 'Dragon', 'Acier', 'Fée', 'Normal', 'Feu', 'Poison', 'Vol'], 'inefficace_contre': ['Poison']},
    'Acier/Spectre': {'faible_contre': ['Combat', 'Sol'], 'resistant_contre': ['Normal', 'Plante', 'Glace', 'Vol', 'Psy', 'Insecte', 'Roche', 'Dragon', 'Acier', 'Fée', 'Poison', 'Insecte'], 'inefficace_contre': ['Normal', 'Spectre']},
    'Acier/Dragon': {'faible_contre': ['Feu', 'Combat', 'Sol'], 'resistant_contre': ['Normal', 'Plante', 'Glace', 'Vol', 'Psy', 'Insecte', 'Roche', 'Dragon', 'Acier', 'Fée', 'Feu', 'Plante', 'Insecte', 'Acier'], 'inefficace_contre': ['Poison']},
    'Acier/Ténèbres': {'faible_contre': ['Combat', 'Sol'], 'resistant_contre': ['Normal', 'Plante', 'Glace', 'Vol', 'Psy', 'Insecte', 'Roche', 'Dragon', 'Acier', 'Fée', 'Ténèbres'], 'inefficace_contre': ['Poison', 'Psy']},
    'Acier/Acier': {'faible_contre': ['Feu', 'Combat', 'Sol'], 'resistant_contre': ['Normal', 'Plante', 'Glace', 'Vol', 'Psy', 'Insecte', 'Roche', 'Dragon', 'Acier', 'Fée'], 'inefficace_contre': ['Poison']},
    'Acier/Fée': {'faible_contre': ['Poison', 'Combat', 'Sol'], 'resistant_contre': ['Normal', 'Plante', 'Glace', 'Vol', 'Psy', 'Insecte', 'Roche', 'Dragon', 'Acier', 'Fée', 'Insecte', 'Ténèbres', 'Fée'], 'inefficace_contre': ['Dragon']},

    # Types Dragon combinés
    'Dragon/Feu': {'faible_contre': ['Glace', 'Dragon', 'Fée'], 'resistant_contre': ['Feu', 'Eau', 'Électrik', 'Plante'], 'inefficace_contre': []},
    'Dragon/Eau': {'faible_contre': ['Électrik', 'Plante', 'Dragon', 'Glace', 'Fée'], 'resistant_contre': ['Feu', 'Eau', 'Plante'], 'inefficace_contre': []},
    'Dragon/Plante': {'faible_contre': ['Feu', 'Glace', 'Poison', 'Vol', 'Insecte', 'Dragon', 'Fée'], 'resistant_contre': ['Eau', 'Électrik', 'Plante'], 'inefficace_contre': []},
    'Dragon/Électrik': {'faible_contre': ['Sol', 'Dragon', 'Glace', 'Fée'], 'resistant_contre': ['Électrik', 'Vol', 'Feu', 'Plante'], 'inefficace_contre': []},
    'Dragon/Glace': {'faible_contre': ['Feu', 'Combat', 'Roche', 'Acier', 'Dragon', 'Fée'], 'resistant_contre': ['Plante', 'Glace'], 'inefficace_contre': []},
    'Dragon/Combat': {'faible_contre': ['Vol', 'Psy', 'Fée', 'Dragon'], 'resistant_contre': ['Plante', 'Roche', 'Insecte', 'Ténèbres'], 'inefficace_contre': []},
    'Dragon/Poison': {'faible_contre': ['Sol', 'Psy', 'Dragon', 'Fée'], 'resistant_contre': ['Plante', 'Poison'], 'inefficace_contre': []},
    'Dragon/Sol': {'faible_contre': ['Eau', 'Glace', 'Dragon', 'Fée'], 'resistant_contre': ['Poison', 'Roche'], 'inefficace_contre': ['Électrik']},
    'Dragon/Vol': {'faible_contre': ['Électrik', 'Glace', 'Roche', 'Dragon', 'Fée'], 'resistant_contre': ['Plante', 'Insecte'], 'inefficace_contre': ['Sol']},
    'Dragon/Psy': {'faible_contre': ['Insecte', 'Spectre', 'Ténèbres', 'Dragon', 'Fée'], 'resistant_contre': ['Psy'], 'inefficace_contre': []},
    'Dragon/Insecte': {'faible_contre': ['Feu', 'Vol', 'Roche', 'Dragon', 'Fée'], 'resistant_contre': ['Plante', 'Sol', 'Insecte'], 'inefficace_contre': []},
    'Dragon/Roche': {'faible_contre': ['Eau', 'Plante', 'Combat', 'Sol', 'Acier', 'Dragon', 'Fée'], 'resistant_contre': ['Normal', 'Feu', 'Poison', 'Vol'], 'inefficace_contre': []},
    'Dragon/Spectre': {'faible_contre': ['Spectre', 'Ténèbres', 'Dragon', 'Fée'], 'resistant_contre': ['Poison', 'Insecte'], 'inefficace_contre': []},
    'Dragon/Dragon': {'faible_contre': ['Glace', 'Dragon', 'Fée'], 'resistant_contre': ['Feu', 'Eau', 'Électrik', 'Plante'], 'inefficace_contre': []},
    'Dragon/Ténèbres': {'faible_contre': ['Combat', 'Insecte', 'Fée', 'Dragon'], 'resistant_contre': ['Ténèbres'], 'inefficace_contre': []},
    'Dragon/Acier': {'faible_contre': ['Feu', 'Combat', 'Sol', 'Dragon', 'Fée'], 'resistant_contre': ['Normal', 'Plante', 'Glace', 'Vol', 'Psy', 'Insecte', 'Roche', 'Dragon', 'Acier', 'Fée'], 'inefficace_contre': []},
    'Dragon/Fée': {'faible_contre': ['Poison', 'Acier'], 'resistant_contre': ['Insecte', 'Ténèbres'], 'inefficace_contre': ['Dragon']},

    # Types Spectre combinés
    'Spectre/Normal': {'faible_contre': ['Spectre', 'Ténèbres'], 'resistant_contre': ['Poison', 'Insecte'], 'inefficace_contre': ['Normal', 'Combat']},
    'Spectre/Feu': {'faible_contre': ['Eau', 'Sol', 'Roche', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Poison', 'Insecte', 'Feu', 'Insecte', 'Fée'], 'inefficace_contre': ['Normal', 'Combat']},
    'Spectre/Eau': {'faible_contre': ['Électrik', 'Plante', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Poison', 'Insecte', 'Feu', 'Eau', 'Glace', 'Acier'], 'inefficace_contre': ['Normal', 'Combat']},
    'Spectre/Plante': {'faible_contre': ['Feu', 'Glace', 'Poison', 'Vol', 'Insecte', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Poison', 'Insecte', 'Eau', 'Électrik', 'Plante', 'Sol'], 'inefficace_contre': ['Normal', 'Combat']},
    'Spectre/Électrik': {'faible_contre': ['Sol', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Électrik', 'Vol', 'Poison', 'Insecte'], 'inefficace_contre': ['Normal', 'Combat']},
    'Spectre/Glace': {'faible_contre': ['Feu', 'Combat', 'Roche', 'Acier', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Poison', 'Insecte', 'Glace'], 'inefficace_contre': ['Normal', 'Combat']},
    'Spectre/Combat': {'faible_contre': ['Vol', 'Psy', 'Fée', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Poison', 'Insecte', 'Roche', 'Ténèbres'], 'inefficace_contre': ['Normal', 'Combat']},
    'Spectre/Poison': {'faible_contre': ['Sol', 'Psy', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Plante', 'Poison', 'Insecte'], 'inefficace_contre': ['Normal', 'Combat']},
    'Spectre/Sol': {'faible_contre': ['Eau', 'Plante', 'Glace', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Poison', 'Roche'], 'inefficace_contre': ['Électrik', 'Normal', 'Combat']},
    'Spectre/Vol': {'faible_contre': ['Électrik', 'Glace', 'Roche', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Plante', 'Insecte'], 'inefficace_contre': ['Sol', 'Normal', 'Combat']},
    'Spectre/Psy': {'faible_contre': ['Insecte', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Psy'], 'inefficace_contre': ['Normal', 'Combat']},
    'Spectre/Insecte': {'faible_contre': ['Feu', 'Vol', 'Roche', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Plante', 'Sol', 'Insecte'], 'inefficace_contre': ['Normal', 'Combat']},
    'Spectre/Roche': {'faible_contre': ['Eau', 'Plante', 'Combat', 'Sol', 'Acier', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Normal', 'Feu', 'Poison', 'Vol'], 'inefficace_contre': ['Normal', 'Combat']},
    'Spectre/Spectre': {'faible_contre': ['Spectre', 'Ténèbres'], 'resistant_contre': ['Poison', 'Insecte'], 'inefficace_contre': ['Normal', 'Combat']},
    'Spectre/Dragon': {'faible_contre': ['Glace', 'Dragon', 'Fée', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Feu', 'Eau', 'Électrik', 'Plante'], 'inefficace_contre': ['Normal', 'Combat']},
    'Spectre/Ténèbres': {'faible_contre': ['Combat', 'Insecte', 'Fée', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Ténèbres'], 'inefficace_contre': ['Psy', 'Normal', 'Combat']},
    'Spectre/Acier': {'faible_contre': ['Feu', 'Combat', 'Sol', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Normal', 'Plante', 'Glace', 'Vol', 'Psy', 'Insecte', 'Roche', 'Dragon', 'Acier', 'Fée'], 'inefficace_contre': ['Poison', 'Normal', 'Combat']},
    'Spectre/Fée': {'faible_contre': ['Poison', 'Acier', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Insecte', 'Ténèbres'], 'inefficace_contre': ['Dragon', 'Normal', 'Combat']},
    
    # Types Roche combinés
    'Roche/Normal': {'faible_contre': ['Eau', 'Plante', 'Combat', 'Sol', 'Acier'], 'resistant_contre': ['Normal', 'Feu', 'Poison', 'Vol'], 'inefficace_contre': []},
    'Roche/Feu': {'faible_contre': ['Eau', 'Sol', 'Roche'], 'resistant_contre': ['Normal', 'Feu', 'Poison', 'Vol', 'Insecte', 'Acier', 'Fée'], 'inefficace_contre': []},
    'Roche/Eau': {'faible_contre': ['Électrik', 'Plante', 'Sol', 'Combat', 'Glace'], 'resistant_contre': ['Normal', 'Poison', 'Vol', 'Feu', 'Roche'], 'inefficace_contre': []},
    'Roche/Plante': {'faible_contre': ['Feu', 'Glace', 'Poison', 'Vol', 'Insecte', 'Combat'], 'resistant_contre': ['Plante', 'Sol', 'Normal', 'Poison', 'Vol'], 'inefficace_contre': []},
    'Roche/Électrik': {'faible_contre': ['Sol', 'Combat', 'Eau', 'Plante'], 'resistant_contre': ['Électrik', 'Vol', 'Normal', 'Poison', 'Roche'], 'inefficace_contre': []},
    'Roche/Glace': {'faible_contre': ['Feu', 'Combat', 'Roche', 'Acier'], 'resistant_contre': ['Glace', 'Normal', 'Poison', 'Vol'], 'inefficace_contre': []},
    'Roche/Combat': {'faible_contre': ['Vol', 'Psy', 'Fée', 'Eau', 'Plante', 'Roche', 'Sol'], 'resistant_contre': ['Insecte', 'Roche', 'Ténèbres', 'Normal', 'Poison', 'Vol'], 'inefficace_contre': []},
    'Roche/Poison': {'faible_contre': ['Sol', 'Psy', 'Roche', 'Eau', 'Plante'], 'resistant_contre': ['Plante', 'Poison', 'Normal', 'Poison', 'Vol'], 'inefficace_contre': []},
    'Roche/Sol': {'faible_contre': ['Eau', 'Plante', 'Glace', 'Combat'], 'resistant_contre': ['Poison', 'Roche', 'Normal', 'Feu', 'Poison', 'Vol'], 'inefficace_contre': ['Électrik']},
    'Roche/Vol': {'faible_contre': ['Électrik', 'Glace', 'Roche', 'Combat', 'Eau', 'Plante'], 'resistant_contre': ['Plante', 'Insecte', 'Normal', 'Feu', 'Poison', 'Vol', 'Roche'], 'inefficace_contre': ['Sol']},
    'Roche/Psy': {'faible_contre': ['Insecte', 'Spectre', 'Ténèbres', 'Eau', 'Plante', 'Roche', 'Sol'], 'resistant_contre': ['Psy', 'Normal', 'Poison', 'Vol'], 'inefficace_contre': []},
    'Roche/Insecte': {'faible_contre': ['Feu', 'Vol', 'Roche', 'Eau', 'Plante'], 'resistant_contre': ['Plante', 'Sol', 'Insecte', 'Normal', 'Poison', 'Vol'], 'inefficace_contre': []},
    'Roche/Roche': {'faible_contre': ['Eau', 'Plante', 'Combat', 'Sol', 'Acier'], 'resistant_contre': ['Normal', 'Feu', 'Poison', 'Vol', 'Roche'], 'inefficace_contre': []},
    'Roche/Spectre': {'faible_contre': ['Spectre', 'Ténèbres', 'Eau', 'Plante', 'Combat', 'Sol', 'Roche'], 'resistant_contre': ['Poison', 'Insecte', 'Normal', 'Feu', 'Poison', 'Vol'], 'inefficace_contre': []},
    'Roche/Dragon': {'faible_contre': ['Glace', 'Dragon', 'Fée', 'Eau', 'Plante', 'Combat', 'Sol', 'Roche'], 'resistant_contre': ['Feu', 'Eau', 'Électrik', 'Plante', 'Roche'], 'inefficace_contre': []},
    'Roche/Ténèbres': {'faible_contre': ['Combat', 'Insecte', 'Fée', 'Eau', 'Plante', 'Sol', 'Roche'], 'resistant_contre': ['Ténèbres', 'Normal', 'Feu', 'Poison', 'Vol'], 'inefficace_contre': []},
    'Roche/Acier': {'faible_contre': ['Feu', 'Combat', 'Sol', 'Eau', 'Plante', 'Roche'], 'resistant_contre': ['Normal', 'Plante', 'Glace', 'Vol', 'Psy', 'Insecte', 'Roche', 'Dragon', 'Acier', 'Fée'], 'inefficace_contre': []},
    'Roche/Fée': {'faible_contre': ['Poison', 'Acier', 'Eau', 'Plante', 'Sol', 'Roche'], 'resistant_contre': ['Insecte', 'Ténèbres', 'Normal', 'Feu', 'Poison', 'Vol'], 'inefficace_contre': []},

    # Types Insecte combinés
    'Insecte/Normal': {'faible_contre': ['Feu', 'Vol', 'Roche', 'Combat'], 'resistant_contre': ['Plante', 'Sol', 'Insecte'], 'inefficace_contre': []},
    'Insecte/Feu': {'faible_contre': ['Eau', 'Sol', 'Roche', 'Feu'], 'resistant_contre': ['Plante', 'Insecte', 'Fée'], 'inefficace_contre': []},
    'Insecte/Eau': {'faible_contre': ['Électrik', 'Plante', 'Sol'], 'resistant_contre': ['Plante', 'Sol', 'Insecte'], 'inefficace_contre': []},
    'Insecte/Plante': {'faible_contre': ['Feu', 'Glace', 'Poison', 'Vol', 'Insecte'], 'resistant_contre': ['Plante', 'Sol', 'Insecte'], 'inefficace_contre': []},
    'Insecte/Électrik': {'faible_contre': ['Sol'], 'resistant_contre': ['Électrik', 'Vol', 'Insecte'], 'inefficace_contre': []},
    'Insecte/Glace': {'faible_contre': ['Feu', 'Combat', 'Roche', 'Acier', 'Vol'], 'resistant_contre': ['Insecte', 'Plante'], 'inefficace_contre': []},
    'Insecte/Combat': {'faible_contre': ['Vol', 'Psy', 'Fée'], 'resistant_contre': ['Insecte', 'Plante', 'Roche', 'Ténèbres'], 'inefficace_contre': []},
    'Insecte/Poison': {'faible_contre': ['Sol', 'Psy', 'Feu'], 'resistant_contre': ['Plante', 'Insecte', 'Fée'], 'inefficace_contre': []},
    'Insecte/Sol': {'faible_contre': ['Eau', 'Plante', 'Glace'], 'resistant_contre': ['Poison', 'Insecte'], 'inefficace_contre': []},
    'Insecte/Vol': {'faible_contre': ['Électrik', 'Glace', 'Roche'], 'resistant_contre': ['Plante', 'Insecte'], 'inefficace_contre': ['Sol']},
    'Insecte/Psy': {'faible_contre': ['Insecte', 'Spectre', 'Ténèbres', 'Feu'], 'resistant_contre': ['Insecte', 'Plante'], 'inefficace_contre': []},
    'Insecte/Insecte': {'faible_contre': ['Feu', 'Vol', 'Roche'], 'resistant_contre': ['Plante', 'Insecte'], 'inefficace_contre': []},
    'Insecte/Roche': {'faible_contre': ['Eau', 'Plante', 'Combat', 'Sol', 'Acier'], 'resistant_contre': ['Plante', 'Insecte', 'Vol'], 'inefficace_contre': []},
    'Insecte/Spectre': {'faible_contre': ['Spectre', 'Ténèbres', 'Feu'], 'resistant_contre': ['Insecte', 'Plante'], 'inefficace_contre': []},
    'Insecte/Dragon': {'faible_contre': ['Glace', 'Dragon', 'Fée', 'Feu'], 'resistant_contre': ['Insecte', 'Plante'], 'inefficace_contre': []},
    'Insecte/Ténèbres': {'faible_contre': ['Combat', 'Insecte', 'Fée', 'Feu'], 'resistant_contre': ['Ténèbres', 'Insecte', 'Plante'], 'inefficace_contre': []},
    'Insecte/Acier': {'faible_contre': ['Feu', 'Combat', 'Sol'], 'resistant_contre': ['Insecte', 'Plante', 'Roche', 'Dragon', 'Acier'], 'inefficace_contre': []},
    'Insecte/Fée': {'faible_contre': ['Poison', 'Acier', 'Feu'], 'resistant_contre': ['Insecte', 'Plante', 'Ténèbres'], 'inefficace_contre': []},
    
    # Types Psy combinés
    'Psy/Normal': {'faible_contre': ['Insecte', 'Spectre', 'Ténèbres', 'Combat'], 'resistant_contre': ['Psy', 'Normal'], 'inefficace_contre': []},
    'Psy/Feu': {'faible_contre': ['Eau', 'Sol', 'Roche', 'Insecte', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Feu', 'Plante', 'Glace', 'Psy', 'Fée'], 'inefficace_contre': []},
    'Psy/Eau': {'faible_contre': ['Électrik', 'Plante', 'Insecte', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Feu', 'Eau', 'Glace', 'Psy'], 'inefficace_contre': []},
    'Psy/Plante': {'faible_contre': ['Feu', 'Glace', 'Poison', 'Vol', 'Insecte', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Eau', 'Électrik', 'Plante', 'Sol', 'Psy'], 'inefficace_contre': []},
    'Psy/Électrik': {'faible_contre': ['Sol', 'Insecte', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Électrik', 'Vol', 'Psy'], 'inefficace_contre': []},
    'Psy/Glace': {'faible_contre': ['Feu', 'Combat', 'Roche', 'Acier', 'Insecte', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Glace', 'Psy'], 'inefficace_contre': []},
    'Psy/Combat': {'faible_contre': ['Vol', 'Psy', 'Fée', 'Insecte', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Insecte', 'Roche', 'Ténèbres', 'Psy', 'Combat'], 'inefficace_contre': []},
    'Psy/Poison': {'faible_contre': ['Sol', 'Psy', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Plante', 'Poison', 'Fée', 'Psy'], 'inefficace_contre': []},
    'Psy/Sol': {'faible_contre': ['Eau', 'Plante', 'Glace', 'Insecte', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Poison', 'Roche', 'Psy'], 'inefficace_contre': []},
    'Psy/Vol': {'faible_contre': ['Électrik', 'Glace', 'Roche', 'Insecte', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Plante', 'Psy'], 'inefficace_contre': ['Sol']},
    'Psy/Psy': {'faible_contre': ['Insecte', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Psy'], 'inefficace_contre': []},
    'Psy/Insecte': {'faible_contre': ['Feu', 'Vol', 'Roche', 'Insecte', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Plante', 'Psy'], 'inefficace_contre': []},
    'Psy/Roche': {'faible_contre': ['Eau', 'Plante', 'Combat', 'Sol', 'Acier', 'Insecte', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Psy', 'Vol', 'Roche'], 'inefficace_contre': []},
    'Psy/Spectre': {'faible_contre': ['Spectre', 'Ténèbres'], 'resistant_contre': ['Psy'], 'inefficace_contre': ['Normal', 'Combat']},
    'Psy/Dragon': {'faible_contre': ['Glace', 'Dragon', 'Fée', 'Insecte', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Psy'], 'inefficace_contre': []},
    'Psy/Ténèbres': {'faible_contre': ['Combat', 'Insecte', 'Fée', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Ténèbres'], 'inefficace_contre': ['Psy']},
    'Psy/Acier': {'faible_contre': ['Feu', 'Combat', 'Sol', 'Insecte', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Psy', 'Acier'], 'inefficace_contre': []},
    'Psy/Fée': {'faible_contre': ['Poison', 'Acier', 'Insecte', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Psy', 'Fée'], 'inefficace_contre': ['Dragon']},

    # Types Vol combinés
    'Vol/Normal': {'faible_contre': ['Électrik', 'Glace', 'Roche', 'Combat'], 'resistant_contre': ['Plante', 'Insecte'], 'inefficace_contre': ['Sol']},
    'Vol/Feu': {'faible_contre': ['Électrik', 'Roche', 'Eau'], 'resistant_contre': ['Plante', 'Insecte', 'Acier', 'Fée', 'Feu'], 'inefficace_contre': ['Sol']},
    'Vol/Eau': {'faible_contre': ['Électrik', 'Glace', 'Roche'], 'resistant_contre': ['Plante', 'Combat', 'Insecte', 'Acier'], 'inefficace_contre': ['Sol']},
    'Vol/Plante': {'faible_contre': ['Feu', 'Glace', 'Électrik', 'Poison', 'Roche'], 'resistant_contre': ['Combat', 'Plante', 'Sol'], 'inefficace_contre': ['Sol']},
    'Vol/Électrik': {'faible_contre': ['Glace', 'Roche'], 'resistant_contre': ['Plante', 'Combat', 'Insecte', 'Électrik', 'Vol'], 'inefficace_contre': ['Sol']},
    'Vol/Glace': {'faible_contre': ['Feu', 'Électrik', 'Roche', 'Combat'], 'resistant_contre': ['Plante', 'Vol', 'Glace'], 'inefficace_contre': ['Sol']},
    'Vol/Combat': {'faible_contre': ['Électrik', 'Glace', 'Roche', 'Psychique'], 'resistant_contre': ['Plante', 'Insecte', 'Ténèbres'], 'inefficace_contre': ['Sol']},
    'Vol/Poison': {'faible_contre': ['Électrik', 'Glace', 'Roche', 'Sol'], 'resistant_contre': ['Plante', 'Combat', 'Insecte', 'Fée'], 'inefficace_contre': ['Sol']},
    'Vol/Sol': {'faible_contre': ['Eau', 'Glace'], 'resistant_contre': ['Plante', 'Insecte'], 'inefficace_contre': []},
    'Vol/Vol': {'faible_contre': ['Électrik', 'Glace', 'Roche'], 'resistant_contre': ['Plante', 'Combat', 'Insecte'], 'inefficace_contre': ['Sol']},
    'Vol/Psy': {'faible_contre': ['Électrik', 'Glace', 'Roche', 'Insecte', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Plante', 'Combat', 'Psy'], 'inefficace_contre': ['Sol']},
    'Vol/Insecte': {'faible_contre': ['Feu', 'Électrik', 'Glace', 'Roche'], 'resistant_contre': ['Plante', 'Combat', 'Sol'], 'inefficace_contre': ['Sol']},
    'Vol/Roche': {'faible_contre': ['Eau', 'Plante', 'Combat', 'Sol'], 'resistant_contre': ['Normal', 'Feu', 'Poison', 'Vol'], 'inefficace_contre': ['Sol']},
    'Vol/Spectre': {'faible_contre': ['Électrik', 'Glace', 'Roche'], 'resistant_contre': ['Insecte', 'Combat'], 'inefficace_contre': ['Sol']},
    'Vol/Dragon': {'faible_contre': ['Glace', 'Électrik', 'Roche'], 'resistant_contre': ['Plante', 'Combat', 'Vol'], 'inefficace_contre': ['Sol']},
    'Vol/Ténèbres': {'faible_contre': ['Électrik', 'Glace', 'Roche', 'Combat'], 'resistant_contre': ['Plante', 'Insecte', 'Ténèbres'], 'inefficace_contre': ['Sol']},
    'Vol/Acier': {'faible_contre': ['Feu', 'Électrik', 'Glace', 'Roche'], 'resistant_contre': ['Plante', 'Combat', 'Vol', 'Insecte', 'Dragon', 'Acier', 'Fée'], 'inefficace_contre': ['Sol']},
    'Vol/Fée': {'faible_contre': ['Électrik', 'Glace', 'Roche'], 'resistant_contre': ['Plante', 'Combat', 'Insecte', 'Fée'], 'inefficace_contre': ['Sol']},

    # Types Sol combinés
    'Sol/Normal': {'faible_contre': ['Eau', 'Glace', 'Plante'], 'resistant_contre': ['Poison', 'Roche'], 'inefficace_contre': ['Électrik']},
    'Sol/Feu': {'faible_contre': ['Eau', 'Plante', 'Glace'], 'resistant_contre': ['Poison', 'Roche', 'Feu', 'Insecte', 'Acier'], 'inefficace_contre': ['Électrik']},
    'Sol/Eau': {'faible_contre': ['Plante'], 'resistant_contre': ['Poison', 'Roche', 'Acier'], 'inefficace_contre': ['Électrik']},
    'Sol/Plante': {'faible_contre': ['Feu', 'Glace', 'Vol', 'Poison'], 'resistant_contre': ['Poison', 'Roche', 'Électrik', 'Plante'], 'inefficace_contre': ['Électrik']},
    'Sol/Électrik': {'faible_contre': ['Eau', 'Glace', 'Plante'], 'resistant_contre': ['Poison', 'Roche'], 'inefficace_contre': []},
    'Sol/Glace': {'faible_contre': ['Feu', 'Combat', 'Roche', 'Eau', 'Plante'], 'resistant_contre': ['Poison', 'Roche', 'Glace'], 'inefficace_contre': ['Électrik']},
    'Sol/Combat': {'faible_contre': ['Eau', 'Glace', 'Vol', 'Psy'], 'resistant_contre': ['Poison', 'Roche', 'Insecte', 'Ténèbres'], 'inefficace_contre': ['Électrik']},
    'Sol/Poison': {'faible_contre': ['Eau', 'Glace', 'Sol', 'Psychique'], 'resistant_contre': ['Plante', 'Poison', 'Roche', 'Fée'], 'inefficace_contre': ['Électrik']},
    'Sol/Vol': {'faible_contre': ['Eau', 'Glace', 'Plante'], 'resistant_contre': ['Poison', 'Roche'], 'inefficace_contre': []},
    'Sol/Psy': {'faible_contre': ['Eau', 'Glace', 'Insecte', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Poison', 'Roche', 'Psy'], 'inefficace_contre': ['Électrik']},
    'Sol/Insecte': {'faible_contre': ['Eau', 'Glace', 'Feu', 'Vol', 'Roche'], 'resistant_contre': ['Plante', 'Poison', 'Roche'], 'inefficace_contre': ['Électrik']},
    'Sol/Roche': {'faible_contre': ['Eau', 'Plante', 'Combat', 'Glace'], 'resistant_contre': ['Poison', 'Roche'], 'inefficace_contre': ['Électrik']},
    'Sol/Spectre': {'faible_contre': ['Eau', 'Glace', 'Insecte', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Poison', 'Roche'], 'inefficace_contre': ['Électrik']},
    'Sol/Dragon': {'faible_contre': ['Eau', 'Glace', 'Dragon', 'Fée', 'Plante'], 'resistant_contre': ['Poison', 'Roche'], 'inefficace_contre': ['Électrik']},
    'Sol/Ténèbres': {'faible_contre': ['Eau', 'Glace', 'Combat', 'Insecte', 'Fée'], 'resistant_contre': ['Poison', 'Roche', 'Ténèbres'], 'inefficace_contre': ['Électrik']},
    'Sol/Acier': {'faible_contre': ['Feu', 'Eau', 'Combat', 'Sol', 'Glace'], 'resistant_contre': ['Poison', 'Roche', 'Acier'], 'inefficace_contre': ['Électrik']},
    'Sol/Fée': {'faible_contre': ['Eau', 'Glace', 'Poison', 'Acier'], 'resistant_contre': ['Poison', 'Roche', 'Ténèbres'], 'inefficace_contre': ['Électrik']},

    # Types Poison combinés
    'Poison/Normal': {'faible_contre': ['Sol', 'Psychique', 'Combat'], 'resistant_contre': ['Plante', 'Poison', 'Fée', 'Insecte'], 'inefficace_contre': []},
    'Poison/Feu': {'faible_contre': ['Sol', 'Psychique', 'Eau', 'Roche'], 'resistant_contre': ['Plante', 'Poison', 'Fée', 'Insecte', 'Feu', 'Acier'], 'inefficace_contre': []},
    'Poison/Eau': {'faible_contre': ['Sol', 'Psychique', 'Électrik', 'Plante'], 'resistant_contre': ['Plante', 'Poison', 'Fée', 'Insecte', 'Eau', 'Acier'], 'inefficace_contre': []},
    'Poison/Plante': {'faible_contre': ['Sol', 'Psychique', 'Feu', 'Glace', 'Vol', 'Insecte'], 'resistant_contre': ['Plante', 'Poison', 'Fée', 'Insecte', 'Électrik', 'Plante'], 'inefficace_contre': []},
    'Poison/Électrik': {'faible_contre': ['Sol', 'Psychique'], 'resistant_contre': ['Plante', 'Poison', 'Fée', 'Insecte', 'Électrik', 'Vol'], 'inefficace_contre': []},
    'Poison/Glace': {'faible_contre': ['Sol', 'Psychique', 'Feu', 'Combat', 'Roche'], 'resistant_contre': ['Plante', 'Poison', 'Fée', 'Insecte', 'Glace'], 'inefficace_contre': []},
    'Poison/Combat': {'faible_contre': ['Sol', 'Psychique', 'Vol', 'Psy', 'Fée'], 'resistant_contre': ['Plante', 'Poison', 'Fée', 'Insecte', 'Roche', 'Ténèbres'], 'inefficace_contre': []},
    'Poison/Poison': {'faible_contre': ['Sol', 'Psychique'], 'resistant_contre': ['Plante', 'Poison', 'Fée', 'Insecte'], 'inefficace_contre': []},
    'Poison/Sol': {'faible_contre': ['Eau', 'Glace', 'Psychique'], 'resistant_contre': ['Poison', 'Plante', 'Fée'], 'inefficace_contre': ['Électrik']},
    'Poison/Vol': {'faible_contre': ['Électrik', 'Psychique', 'Glace', 'Roche'], 'resistant_contre': ['Plante', 'Poison', 'Fée', 'Insecte'], 'inefficace_contre': []},
    'Poison/Psy': {'faible_contre': ['Sol', 'Insecte', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Plante', 'Poison', 'Fée', 'Insecte', 'Psy'], 'inefficace_contre': []},
    'Poison/Insecte': {'faible_contre': ['Feu', 'Sol', 'Psychique', 'Vol', 'Roche'], 'resistant_contre': ['Plante', 'Poison', 'Fée', 'Insecte'], 'inefficace_contre': []},
    'Poison/Roche': {'faible_contre': ['Eau', 'Plante', 'Combat', 'Sol', 'Psychique'], 'resistant_contre': ['Plante', 'Poison', 'Fée', 'Insecte'], 'inefficace_contre': []},
    'Poison/Spectre': {'faible_contre': ['Spectre', 'Ténèbres', 'Sol', 'Psychique'], 'resistant_contre': ['Plante', 'Poison', 'Fée', 'Insecte'], 'inefficace_contre': []},
    'Poison/Dragon': {'faible_contre': ['Glace', 'Dragon', 'Fée', 'Sol', 'Psychique'], 'resistant_contre': ['Plante', 'Poison', 'Fée', 'Insecte'], 'inefficace_contre': []},
    'Poison/Ténèbres': {'faible_contre': ['Combat', 'Insecte', 'Fée', 'Sol', 'Psychique'], 'resistant_contre': ['Plante', 'Poison', 'Fée', 'Insecte', 'Ténèbres'], 'inefficace_contre': []},
    'Poison/Acier': {'faible_contre': ['Feu', 'Combat', 'Sol', 'Psychique'], 'resistant_contre': ['Plante', 'Poison', 'Fée', 'Insecte', 'Acier'], 'inefficace_contre': []},
    'Poison/Fée': {'faible_contre': ['Poison', 'Acier', 'Sol', 'Psychique'], 'resistant_contre': ['Plante', 'Poison', 'Fée', 'Insecte'], 'inefficace_contre': []},

    # Types Combat combinés
    'Combat/Normal': {'faible_contre': ['Vol', 'Psy'], 'resistant_contre': ['Insecte', 'Roche', 'Ténèbres'], 'inefficace_contre': []},
    'Combat/Feu': {'faible_contre': ['Vol', 'Psy', 'Eau', 'Sol', 'Roche'], 'resistant_contre': ['Insecte', 'Roche', 'Ténèbres', 'Feu', 'Glace'], 'inefficace_contre': []},
    'Combat/Eau': {'faible_contre': ['Vol', 'Psy', 'Électrik', 'Plante'], 'resistant_contre': ['Insecte', 'Roche', 'Ténèbres', 'Feu', 'Eau', 'Glace', 'Acier'], 'inefficace_contre': []},
    'Combat/Plante': {'faible_contre': ['Vol', 'Psy', 'Feu', 'Glace', 'Poison', 'Insecte'], 'resistant_contre': ['Insecte', 'Roche', 'Ténèbres', 'Eau', 'Électrik', 'Plante', 'Sol'], 'inefficace_contre': []},
    'Combat/Électrik': {'faible_contre': ['Vol', 'Psy', 'Sol'], 'resistant_contre': ['Insecte', 'Roche', 'Ténèbres', 'Électrik', 'Vol', 'Acier'], 'inefficace_contre': []},
    'Combat/Glace': {'faible_contre': ['Vol', 'Psy', 'Feu', 'Combat', 'Roche', 'Acier'], 'resistant_contre': ['Insecte', 'Roche', 'Ténèbres', 'Glace'], 'inefficace_contre': []},
    'Combat/Combat': {'faible_contre': ['Vol', 'Psy', 'Fée'], 'resistant_contre': ['Insecte', 'Roche', 'Ténèbres'], 'inefficace_contre': []},
    'Combat/Poison': {'faible_contre': ['Vol', 'Psy', 'Sol', 'Fée'], 'resistant_contre': ['Insecte', 'Roche', 'Ténèbres', 'Plante', 'Poison'], 'inefficace_contre': []},
    'Combat/Sol': {'faible_contre': ['Vol', 'Eau', 'Glace'], 'resistant_contre': ['Insecte', 'Roche', 'Ténèbres', 'Poison', 'Roche', 'Sol'], 'inefficace_contre': []},
    'Combat/Vol': {'faible_contre': ['Électrik', 'Glace', 'Roche', 'Psy'], 'resistant_contre': ['Insecte', 'Roche', 'Ténèbres', 'Plante', 'Combat'], 'inefficace_contre': []},
    'Combat/Psy': {'faible_contre': ['Insecte', 'Spectre', 'Ténèbres', 'Vol'], 'resistant_contre': ['Insecte', 'Roche', 'Ténèbres', 'Combat', 'Psy'], 'inefficace_contre': []},
    'Combat/Insecte': {'faible_contre': ['Feu', 'Vol', 'Roche', 'Psy'], 'resistant_contre': ['Insecte', 'Roche', 'Ténèbres', 'Plante', 'Combat', 'Sol'], 'inefficace_contre': []},
    'Combat/Roche': {'faible_contre': ['Eau', 'Plante', 'Combat', 'Sol', 'Fée'], 'resistant_contre': ['Insecte', 'Roche', 'Ténèbres', 'Normal', 'Feu', 'Poison', 'Vol'], 'inefficace_contre': []},
    'Combat/Spectre': {'faible_contre': ['Spectre', 'Ténèbres', 'Vol', 'Psy'], 'resistant_contre': ['Insecte', 'Roche', 'Ténèbres'], 'inefficace_contre': ['Normal', 'Combat']},
    'Combat/Dragon': {'faible_contre': ['Glace', 'Dragon', 'Fée', 'Vol', 'Psy'], 'resistant_contre': ['Insecte', 'Roche', 'Ténèbres', 'Feu', 'Eau', 'Électrik', 'Plante'], 'inefficace_contre': []},
    'Combat/Ténèbres': {'faible_contre': ['Combat', 'Fée', 'Vol', 'Psy'], 'resistant_contre': ['Insecte', 'Roche', 'Ténèbres'], 'inefficace_contre': []},
    'Combat/Acier': {'faible_contre': ['Feu', 'Combat', 'Sol', 'Vol', 'Psy'], 'resistant_contre': ['Insecte', 'Roche', 'Ténèbres', 'Normal', 'Plante', 'Glace', 'Vol', 'Psy', 'Insecte', 'Roche', 'Dragon', 'Acier', 'Fée'], 'inefficace_contre': []},
    'Combat/Fée': {'faible_contre': ['Poison', 'Acier', 'Vol', 'Psy'], 'resistant_contre': ['Insecte', 'Roche', 'Ténèbres', 'Combat', 'Fée'], 'inefficace_contre': []},

    # Types Glace combinés
    'Glace/Normal': {'faible_contre': ['Feu', 'Combat', 'Roche', 'Acier'], 'resistant_contre': ['Glace'], 'inefficace_contre': []},
    'Glace/Feu': {'faible_contre': ['Feu', 'Combat', 'Roche', 'Acier'], 'resistant_contre': ['Glace', 'Insecte', 'Fée', 'Plante'], 'inefficace_contre': []},
    'Glace/Eau': {'faible_contre': ['Électrik', 'Plante', 'Feu', 'Combat', 'Roche', 'Acier'], 'resistant_contre': ['Glace', 'Eau'], 'inefficace_contre': []},
    'Glace/Plante': {'faible_contre': ['Feu', 'Combat', 'Roche', 'Acier', 'Poison', 'Vol', 'Insecte'], 'resistant_contre': ['Glace', 'Eau', 'Électrik', 'Plante', 'Sol'], 'inefficace_contre': []},
    'Glace/Électrik': {'faible_contre': ['Feu', 'Combat', 'Roche', 'Acier', 'Sol'], 'resistant_contre': ['Glace', 'Électrik', 'Vol', 'Acier'], 'inefficace_contre': []},
    'Glace/Glace': {'faible_contre': ['Feu', 'Combat', 'Roche', 'Acier'], 'resistant_contre': ['Glace'], 'inefficace_contre': []},
    'Glace/Combat': {'faible_contre': ['Vol', 'Psy', 'Feu', 'Roche', 'Acier'], 'resistant_contre': ['Insecte', 'Ténèbres', 'Glace'], 'inefficace_contre': []},
    'Glace/Poison': {'faible_contre': ['Sol', 'Psy', 'Feu', 'Combat', 'Roche', 'Acier'], 'resistant_contre': ['Glace', 'Plante', 'Poison'], 'inefficace_contre': []},
    'Glace/Sol': {'faible_contre': ['Eau', 'Plante', 'Combat', 'Glace', 'Roche', 'Acier'], 'resistant_contre': ['Poison', 'Roche', 'Glace', 'Sol'], 'inefficace_contre': ['Électrik']},
    'Glace/Vol': {'faible_contre': ['Électrik', 'Feu', 'Glace', 'Roche', 'Combat'], 'resistant_contre': ['Plante', 'Insecte', 'Glace'], 'inefficace_contre': ['Sol']},
    'Glace/Psy': {'faible_contre': ['Insecte', 'Spectre', 'Ténèbres', 'Feu', 'Combat', 'Roche', 'Acier'], 'resistant_contre': ['Glace', 'Psy'], 'inefficace_contre': []},
    'Glace/Insecte': {'faible_contre': ['Feu', 'Vol', 'Roche', 'Combat', 'Acier'], 'resistant_contre': ['Glace', 'Plante', 'Sol'], 'inefficace_contre': []},
    'Glace/Roche': {'faible_contre': ['Eau', 'Plante', 'Combat', 'Sol', 'Acier', 'Feu'], 'resistant_contre': ['Glace', 'Normal', 'Poison', 'Vol'], 'inefficace_contre': []},
    'Glace/Spectre': {'faible_contre': ['Spectre', 'Ténèbres', 'Feu', 'Combat', 'Roche', 'Acier'], 'resistant_contre': ['Glace', 'Poison', 'Insecte'], 'inefficace_contre': []},
    'Glace/Dragon': {'faible_contre': ['Glace', 'Dragon', 'Fée', 'Feu', 'Combat', 'Roche', 'Acier'], 'resistant_contre': ['Glace', 'Feu', 'Eau', 'Électrik', 'Plante'], 'inefficace_contre': []},
    'Glace/Ténèbres': {'faible_contre': ['Combat', 'Fée', 'Feu', 'Roche', 'Acier'], 'resistant_contre': ['Glace', 'Ténèbres'], 'inefficace_contre': []},
    'Glace/Acier': {'faible_contre': ['Feu', 'Combat', 'Sol', 'Roche', 'Acier'], 'resistant_contre': ['Glace', 'Normal', 'Plante', 'Vol', 'Psy', 'Insecte', 'Dragon', 'Fée'], 'inefficace_contre': []},
    'Glace/Fée': {'faible_contre': ['Poison', 'Acier', 'Feu', 'Combat', 'Roche'], 'resistant_contre': ['Glace', 'Insecte', 'Ténèbres', 'Fée'], 'inefficace_contre': []},

    # Types Eletrik combinés
    'Électrik/Normal': {'faible_contre': ['Sol', 'Combat'], 'resistant_contre': ['Électrik', 'Vol'], 'inefficace_contre': ['Spectre']},
    'Électrik/Feu': {'faible_contre': ['Sol', 'Eau'], 'resistant_contre': ['Feu', 'Électrik', 'Vol', 'Acier'], 'inefficace_contre': []},
    'Électrik/Eau': {'faible_contre': ['Sol'], 'resistant_contre': ['Feu', 'Électrik', 'Vol', 'Acier'], 'inefficace_contre': []},
    'Électrik/Plante': {'faible_contre': ['Feu', 'Sol'], 'resistant_contre': ['Électrik', 'Vol', 'Plante', 'Acier'], 'inefficace_contre': []},
    'Électrik/Électrik': {'faible_contre': ['Sol'], 'resistant_contre': ['Électrik', 'Vol', 'Acier'], 'inefficace_contre': []},
    'Électrik/Glace': {'faible_contre': ['Feu', 'Sol', 'Combat', 'Roche', 'Acier'], 'resistant_contre': ['Électrik', 'Vol', 'Glace', 'Acier'], 'inefficace_contre': []},
    'Électrik/Combat': {'faible_contre': ['Sol', 'Vol', 'Psy', 'Fée'], 'resistant_contre': ['Électrik', 'Insecte', 'Roche', 'Ténèbres'], 'inefficace_contre': []},
    'Électrik/Poison': {'faible_contre': ['Sol'], 'resistant_contre': ['Électrik', 'Poison', 'Insecte', 'Fée'], 'inefficace_contre': []},
    'Électrik/Sol': {'faible_contre': [], 'resistant_contre': ['Poison', 'Roche'], 'inefficace_contre': ['Électrik']},
    'Électrik/Vol': {'faible_contre': ['Électrik', 'Glace', 'Roche'], 'resistant_contre': ['Plante', 'Insecte'], 'inefficace_contre': ['Sol']},
    'Électrik/Psy': {'faible_contre': ['Sol', 'Insecte', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Électrik', 'Psy'], 'inefficace_contre': []},
    'Électrik/Insecte': {'faible_contre': ['Feu', 'Sol', 'Vol', 'Roche', 'Combat'], 'resistant_contre': ['Électrik', 'Plante', 'Sol'], 'inefficace_contre': []},
    'Électrik/Roche': {'faible_contre': ['Eau', 'Sol', 'Combat'], 'resistant_contre': ['Électrik', 'Normal', 'Poison', 'Vol'], 'inefficace_contre': []},
    'Électrik/Spectre': {'faible_contre': ['Sol', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Électrik', 'Poison', 'Insecte'], 'inefficace_contre': ['Normal', 'Combat']},
    'Électrik/Dragon': {'faible_contre': ['Glace', 'Sol', 'Dragon', 'Fée'], 'resistant_contre': ['Électrik', 'Feu', 'Eau', 'Plante'], 'inefficace_contre': []},
    'Électrik/Ténèbres': {'faible_contre': ['Sol', 'Combat', 'Insecte', 'Fée'], 'resistant_contre': ['Électrik', 'Ténèbres'], 'inefficace_contre': ['Psy']},
    'Électrik/Acier': {'faible_contre': ['Feu', 'Sol', 'Combat'], 'resistant_contre': ['Électrik', 'Normal', 'Plante', 'Vol', 'Psy', 'Insecte', 'Dragon', 'Fée'], 'inefficace_contre': ['Poison']},
    'Électrik/Fée': {'faible_contre': ['Poison', 'Acier', 'Sol'], 'resistant_contre': ['Électrik', 'Insecte', 'Ténèbres', 'Fée'], 'inefficace_contre': ['Dragon']},

    # Types Plante combinés
    'Plante/Normal': {'faible_contre': ['Feu', 'Glace', 'Poison', 'Vol', 'Insecte'], 'resistant_contre': ['Eau', 'Électrik', 'Plante', 'Sol'], 'inefficace_contre': []},
    'Plante/Feu': {'faible_contre': ['Feu', 'Glace', 'Poison', 'Vol', 'Insecte', 'Eau', 'Sol', 'Roche'], 'resistant_contre': ['Plante', 'Insecte', 'Acier', 'Fée'], 'inefficace_contre': []},
    'Plante/Eau': {'faible_contre': ['Feu', 'Glace', 'Poison', 'Vol', 'Insecte'], 'resistant_contre': ['Eau', 'Électrik', 'Plante', 'Sol'], 'inefficace_contre': []},
    'Plante/Électrik': {'faible_contre': ['Feu', 'Glace', 'Poison', 'Vol', 'Insecte'], 'resistant_contre': ['Électrik', 'Plante', 'Sol'], 'inefficace_contre': []},
    'Plante/Plante': {'faible_contre': ['Feu', 'Glace', 'Poison', 'Vol', 'Insecte'], 'resistant_contre': ['Eau', 'Électrik', 'Plante', 'Sol'], 'inefficace_contre': []},
    'Plante/Glace': {'faible_contre': ['Feu', 'Glace', 'Poison', 'Vol', 'Insecte', 'Combat', 'Roche', 'Acier'], 'resistant_contre': ['Eau', 'Électrik', 'Plante', 'Sol', 'Glace'], 'inefficace_contre': []},
    'Plante/Combat': {'faible_contre': ['Feu', 'Glace', 'Poison', 'Vol', 'Insecte', 'Vol', 'Psy', 'Fée'], 'resistant_contre': ['Eau', 'Électrik', 'Plante', 'Sol', 'Insecte', 'Roche', 'Ténèbres'], 'inefficace_contre': []},
    'Plante/Poison': {'faible_contre': ['Feu', 'Glace', 'Poison', 'Vol', 'Insecte', 'Sol', 'Psy'], 'resistant_contre': ['Eau', 'Plante', 'Poison', 'Fée'], 'inefficace_contre': []},
    'Plante/Sol': {'faible_contre': ['Feu', 'Glace', 'Vol', 'Insecte'], 'resistant_contre': ['Plante', 'Électrik', 'Poison', 'Roche'], 'inefficace_contre': ['Électrik']},
    'Plante/Vol': {'faible_contre': ['Feu', 'Glace', 'Poison', 'Roche', 'Insecte'], 'resistant_contre': ['Plante', 'Sol'], 'inefficace_contre': ['Sol']},
    'Plante/Psy': {'faible_contre': ['Feu', 'Glace', 'Poison', 'Vol', 'Insecte', 'Insecte', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Eau', 'Électrik', 'Plante', 'Sol', 'Psy'], 'inefficace_contre': []},
    'Plante/Insecte': {'faible_contre': ['Feu', 'Glace', 'Poison', 'Vol', 'Roche'], 'resistant_contre': ['Eau', 'Électrik', 'Plante', 'Sol'], 'inefficace_contre': []},
    'Plante/Roche': {'faible_contre': ['Feu', 'Glace', 'Poison', 'Vol', 'Insecte', 'Eau', 'Plante', 'Combat', 'Sol', 'Acier'], 'resistant_contre': ['Plante', 'Électrik', 'Poison', 'Vol'], 'inefficace_contre': []},
    'Plante/Spectre': {'faible_contre': ['Feu', 'Glace', 'Poison', 'Vol', 'Insecte', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Eau', 'Électrik', 'Plante', 'Sol', 'Poison', 'Insecte'], 'inefficace_contre': ['Normal', 'Combat']},
    'Plante/Dragon': {'faible_contre': ['Feu', 'Glace', 'Poison', 'Vol', 'Insecte', 'Glace', 'Dragon', 'Fée'], 'resistant_contre': ['Eau', 'Électrik', 'Plante', 'Sol', 'Feu', 'Eau', 'Électrik', 'Plante'], 'inefficace_contre': []},
    'Plante/Ténèbres': {'faible_contre': ['Feu', 'Glace', 'Poison', 'Vol', 'Insecte', 'Combat', 'Insecte', 'Fée'], 'resistant_contre': ['Eau', 'Électrik', 'Plante', 'Sol', 'Ténèbres'], 'inefficace_contre': ['Psy']},
    'Plante/Acier': {'faible_contre': ['Feu', 'Glace', 'Poison', 'Vol', 'Insecte', 'Feu', 'Combat', 'Sol'], 'resistant_contre': ['Eau', 'Électrik', 'Plante', 'Sol', 'Normal', 'Plante', 'Glace', 'Vol', 'Psy', 'Insecte', 'Roche', 'Dragon', 'Acier', 'Fée'], 'inefficace_contre': ['Poison']},
    'Plante/Fée': {'faible_contre': ['Feu', 'Glace', 'Poison', 'Vol', 'Insecte', 'Poison', 'Acier'], 'resistant_contre': ['Eau', 'Électrik', 'Plante', 'Sol', 'Combat', 'Insecte', 'Ténèbres', 'Fée'], 'inefficace_contre': ['Dragon']},    

    # Types Eau combinés
    'Eau/Normal': {'faible_contre': ['Électrik', 'Plante', 'Combat'], 'resistant_contre': ['Feu', 'Eau', 'Glace', 'Acier'], 'inefficace_contre': []},
    'Eau/Feu': {'faible_contre': ['Électrik', 'Sol', 'Roche'], 'resistant_contre': ['Feu', 'Glace', 'Acier', 'Insecte', 'Fée'], 'inefficace_contre': []},
    'Eau/Plante': {'faible_contre': ['Électrik', 'Feu', 'Glace', 'Poison', 'Vol', 'Insecte'], 'resistant_contre': ['Eau', 'Plante', 'Sol'], 'inefficace_contre': []},
    'Eau/Électrik': {'faible_contre': ['Sol'], 'resistant_contre': ['Électrik', 'Vol', 'Acier', 'Feu', 'Eau', 'Glace'], 'inefficace_contre': []},
    'Eau/Glace': {'faible_contre': ['Électrik', 'Feu', 'Combat', 'Roche', 'Acier'], 'resistant_contre': ['Eau', 'Glace'], 'inefficace_contre': []},
    'Eau/Combat': {'faible_contre': ['Électrik', 'Vol', 'Psy', 'Fée'], 'resistant_contre': ['Feu', 'Eau', 'Glace', 'Acier', 'Insecte', 'Roche', 'Ténèbres'], 'inefficace_contre': []},
    'Eau/Poison': {'faible_contre': ['Électrik', 'Sol', 'Psy'], 'resistant_contre': ['Eau', 'Plante', 'Poison', 'Fée'], 'inefficace_contre': []},
    'Eau/Sol': {'faible_contre': ['Plante'], 'resistant_contre': ['Poison', 'Roche', 'Feu', 'Eau', 'Glace', 'Acier'], 'inefficace_contre': ['Électrik']},
    'Eau/Vol': {'faible_contre': ['Électrik', 'Roche'], 'resistant_contre': ['Plante', 'Insecte', 'Feu', 'Eau', 'Glace', 'Acier'], 'inefficace_contre': ['Sol']},
    'Eau/Psy': {'faible_contre': ['Électrik', 'Insecte', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Feu', 'Eau', 'Glace', 'Acier', 'Psy'], 'inefficace_contre': []},
    'Eau/Insecte': {'faible_contre': ['Électrik', 'Feu', 'Vol', 'Roche'], 'resistant_contre': ['Eau', 'Plante', 'Glace', 'Sol'], 'inefficace_contre': []},
    'Eau/Roche': {'faible_contre': ['Électrik', 'Plante', 'Combat', 'Sol', 'Acier'], 'resistant_contre': ['Feu', 'Eau', 'Glace', 'Vol', 'Insecte', 'Poison'], 'inefficace_contre': []},
    'Eau/Spectre': {'faible_contre': ['Électrik', 'Spectre', 'Ténèbres'], 'resistant_contre': ['Feu', 'Eau', 'Glace', 'Acier', 'Poison', 'Insecte'], 'inefficace_contre': ['Normal', 'Combat']},
    'Eau/Dragon': {'faible_contre': ['Électrik', 'Glace', 'Dragon', 'Fée'], 'resistant_contre': ['Feu', 'Eau', 'Plante', 'Électrik'], 'inefficace_contre': []},
    'Eau/Ténèbres': {'faible_contre': ['Électrik', 'Combat', 'Insecte', 'Fée'], 'resistant_contre': ['Feu', 'Eau', 'Glace', 'Acier', 'Ténèbres'], 'inefficace_contre': ['Psy']},
    'Eau/Acier': {'faible_contre': ['Électrik', 'Feu', 'Combat', 'Sol'], 'resistant_contre': ['Feu', 'Eau', 'Glace', 'Acier', 'Plante', 'Normal', 'Vol', 'Psy', 'Insecte', 'Roche', 'Dragon', 'Fée'], 'inefficace_contre': ['Poison']},
    'Eau/Fée': {'faible_contre': ['Électrik', 'Poison', 'Acier'], 'resistant_contre': ['Feu', 'Eau', 'Glace', 'Acier', 'Combat', 'Insecte', 'Ténèbres', 'Fée'], 'inefficace_contre': ['Dragon']},

    # Types Feu combinés
    'Feu/Normal': {'faible_contre': ['Eau', 'Sol', 'Roche', 'Combat'], 'resistant_contre': ['Feu', 'Plante', 'Glace', 'Insecte', 'Acier', 'Fée'], 'inefficace_contre': ['Spectre']},
    'Feu/Eau': {'faible_contre': ['Électrik', 'Sol', 'Roche'], 'resistant_contre': ['Feu', 'Glace', 'Acier', 'Insecte', 'Fée'], 'inefficace_contre': []},
    'Feu/Plante': {'faible_contre': ['Eau', 'Sol', 'Roche'], 'resistant_contre': ['Feu', 'Plante', 'Glace', 'Insecte', 'Acier', 'Fée'], 'inefficace_contre': []},
    'Feu/Électrik': {'faible_contre': ['Sol', 'Eau'], 'resistant_contre': ['Feu', 'Glace', 'Insecte', 'Acier', 'Fée', 'Électrik', 'Vol'], 'inefficace_contre': []},
    'Feu/Glace': {'faible_contre': ['Feu', 'Combat', 'Roche', 'Acier'], 'resistant_contre': ['Plante', 'Insecte', 'Fée', 'Feu'], 'inefficace_contre': []},
    'Feu/Combat': {'faible_contre': ['Vol', 'Psy', 'Fée', 'Eau', 'Sol', 'Roche'], 'resistant_contre': ['Insecte', 'Roche', 'Ténèbres', 'Feu', 'Glace'], 'inefficace_contre': []},
    'Feu/Poison': {'faible_contre': ['Sol', 'Psy', 'Roche', 'Eau'], 'resistant_contre': ['Plante', 'Feu', 'Fée', 'Insecte'], 'inefficace_contre': []},
    'Feu/Sol': {'faible_contre': ['Eau', 'Plante'], 'resistant_contre': ['Poison', 'Roche', 'Feu', 'Insecte', 'Acier'], 'inefficace_contre': ['Électrik']},
    'Feu/Vol': {'faible_contre': ['Électrik', 'Eau', 'Roche'], 'resistant_contre': ['Plante', 'Insecte', 'Acier', 'Fée', 'Feu', 'Combat', 'Glace'], 'inefficace_contre': ['Sol']},
    'Feu/Psy': {'faible_contre': ['Insecte', 'Spectre', 'Ténèbres', 'Eau', 'Sol', 'Roche'], 'resistant_contre': ['Combat', 'Psy', 'Feu', 'Insecte'], 'inefficace_contre': []},
    'Feu/Insecte': {'faible_contre': ['Feu', 'Vol', 'Roche', 'Eau'], 'resistant_contre': ['Plante', 'Feu', 'Insecte'], 'inefficace_contre': []},
    'Feu/Roche': {'faible_contre': ['Eau', 'Plante', 'Combat', 'Sol', 'Acier'], 'resistant_contre': ['Normal', 'Feu', 'Poison', 'Vol', 'Insecte', 'Fée'], 'inefficace_contre': []},
    'Feu/Spectre': {'faible_contre': ['Spectre', 'Ténèbres', 'Eau', 'Sol', 'Roche'], 'resistant_contre': ['Poison', 'Insecte', 'Feu'], 'inefficace_contre': ['Normal', 'Combat']},
    'Feu/Dragon': {'faible_contre': ['Glace', 'Dragon', 'Fée', 'Eau', 'Sol', 'Roche'], 'resistant_contre': ['Feu', 'Plante', 'Insecte', 'Acier'], 'inefficace_contre': []},
    'Feu/Ténèbres': {'faible_contre': ['Combat', 'Insecte', 'Fée', 'Eau', 'Sol', 'Roche'], 'resistant_contre': ['Spectre', 'Ténèbres', 'Feu', 'Insecte'], 'inefficace_contre': ['Psy']},
    'Feu/Acier': {'faible_contre': ['Feu', 'Combat', 'Sol', 'Eau'], 'resistant_contre': ['Normal', 'Plante', 'Glace', 'Vol', 'Psy', 'Insecte', 'Roche', 'Dragon', 'Acier', 'Fée'], 'inefficace_contre': ['Poison']},
    'Feu/Fée': {'faible_contre': ['Poison', 'Acier', 'Eau', 'Sol', 'Roche'], 'resistant_contre': ['Combat', 'Insecte', 'Ténèbres', 'Feu', 'Fée'], 'inefficace_contre': ['Dragon']}
}
